export const projectsData = [
    {
        id: 1,
        src: "/images/projects/cozyliv-1.png",
        src2: "/images/projects/cozyliv-2.png",
        src3: "/images/projects/cozyliv-3.png",
        category: "Development",
        title: "Cozyliv website",
        date:  "2024",
        client: "Human Booster",
        description: "RESTful web application built on a client-server architecture for coliving space rentals, targeting young professionals. The backend exposes a REST API developed in PHP using Symfony and API Platform, connected to a MySQL database. The frontend is a responsive Single Page Application (SPA) developed in Angular. I also handled the UI/UX design using Figma.",
    },
    {
        id: 2,
        src: "/images/projects/alts-1.png",
        src2: "/images/projects/alts-2.png",
        src3: "/images/projects/alts-3.png",
        category: "Web design",
        title: "Association loisir & tourisme social",
        date:  "2018",
        client: "ALTS",
        description: "Responsive website developed for ALTS (Association Loisirs et Tourisme Social), based in Lyon. The project included the creation of a custom WordPress theme tailored to the association’s needs, deployment on an OVH production server, configuration of SMTP for reliable email delivery (contact forms, notifications), and implementation of ongoing technical maintenance. The visual identity was also designed to align with the association’s values and audience.",
    },
    {
        id: 3,
        src: "/images/projects/jlub-1.png",
        src2: "/images/projects/jlub-2.png",
        src3: "/images/projects/jlub-3.png",
        category: "Web design",
        title: "Je loue un box",
        date:  "2020",
        client: "Je loue un box",
        description: "Showcase website for a storage and self-storage rental company based in Blanzy, Saône-et-Loire. The project involved brand identity design, custom responsive WordPress theme development, deployment on an OVH production server, SMTP-based email integration for contact forms and automated notifications, and ongoing technical maintenance.",
    },
    {
        id: 4,
        src: "/images/projects/elomar.png",
        category: "Web design",
        title: "Elomar one-page website",
        date:  "2019",
        client: "Elomar",
        description: "One-page responsive website for Elomar, a company renting industrial buildings to businesses. The project included visual identity design, custom WordPress theme development, OVH deployment, SMTP email integration, and ongoing maintenance.",
    },
    {
        id: 5,
        src: "/images/projects/multiprise-1.png",
        src2: "/images/projects/multiprise-2.png",
        src3: "/images/projects/multiprise-3.png",
        category: "Graphic design",
        title: "Multiprise",
        date:  "2013-2018",
        client: "CMCAS EDF-GDF Lyon",
        description: "A 16-page monthly publication showcasing the activities and initiatives of the EDF-GDF Social Welfare Mutual Fund (Caisse Mutuelle Complémentaire d’Action Sociale) in the city of Lyon. The magazine highlights community programs, member services, and local events. I was responsible for the creation of the visual identity (graphic charter) and handled the full layout and production of each issue.",
    },
    {
        id: 6,
        src: "/images/projects/magnanville.png",
        category: "Graphic design",
        title: "Magazine Magnanville",
        date:  "2015",
        client: "Magnanville municipality",
        description: "A 24-page bimonthly municipal bulletin showcasing the sports, cultural, and community activities of the city of Magnanville, along with coverage of local events and initiatives. I was in charge of the graphic design and created a complete, ready-to-use layout template and visual identity. The template was then handed off for ongoing use by the municipality.",
    },

]